# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'seminar4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for seminar4
  pod 'RxSwift'
  pod 'RxAppState'
  pod 'RxDataSources'
  pod 'Alamofire'
  pod 'Kingfisher'
end
