# Generated by Django 3.2.6 on 2021-09-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='university',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seminar',
            name='name',
            field=models.CharField(default='seminar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userseminar',
            name='dropped_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userseminar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userseminar',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
