# Generated by Django 3.2.6 on 2021-10-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0004_auto_20210925_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
