# Generated by Django 3.2.6 on 2021-10-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_alter_seminar_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
