# Generated by Django 3.2.6 on 2021-08-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.PositiveSmallIntegerField(choices=[(1, 'very low'), (2, 'low'), (3, 'middle'), (4, 'high'), (5, 'very_high')])),
                ('rdb', models.PositiveSmallIntegerField(choices=[(1, 'very low'), (2, 'low'), (3, 'middle'), (4, 'high'), (5, 'very_high')])),
                ('programming', models.PositiveSmallIntegerField(choices=[(1, 'very low'), (2, 'low'), (3, 'middle'), (4, 'high'), (5, 'very_high')])),
                ('major', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
                ('backend_reason', models.CharField(max_length=500)),
                ('waffle_reason', models.CharField(blank=True, max_length=500)),
                ('say_something', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='survey.operatingsystem')),
            ],
        ),
    ]
