# Generated by Django 3.2.6 on 2021-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_auto_20210923_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='accepted',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='university',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
